Minimum-Y: 100

Join-Message:
  - "&b&lBow Boost Practice"
  - "&7This game mode allows you to practice"
  - "&7your \"Bow Boosting\" skills."
  - ""
  - "&e&oPlease execute the command /start to start practicing."